language: node_js

node_js:
  - 12

cache: npm

services:
  - docker

branches:
  only:
    - master

jobs:
  include:
    - stage: Tests
      name: Cocode Client Test
      before_install:
        - cd ./cocode
      install:
        - npm install
      script:
        - npm run test
    - name: API Server Test
      before_install:
        - cd ./api-server
      install:
        - npm install
      script:
        - npm run test
